### ISSUE TITLE
[Android] Out of memory error with big images

### ISSUE THREAD

**Issue by Svajoklis-** [marcshilling/react-native-image-picker#116]
We are using this library in our project and we are resizing images to {maxWidth: 1024, maxHeight: 1024}. When we try to pick an image that's very large (16 MB in size) the showImagePicker method crashes with:

`FATAL EXCEPTION: main
                                                                                    Process: com.devbridge.TeamApp2_Android.debug, PID: 2504
                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 203079692 byte allocation with 4194304 free bytes and 53MB until OOM
                                                                                        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                                        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
                                                                                        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
                                                                                        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
                                                                                        at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:417)
                                                                                        at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:495)
                                                                                        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:400)
                                                                                        at com.imagepicker.ImagePickerPackage.handleActivityResult(ImagePickerPackage.java:46)`

The issue is not apparent in Android Emulator with enough VM Heap size, but when it's reduced to realistic sizes (64 for example) or when testing on a real device - application crashes as soon as it tries to resize the image.

**Comment by yfuks** [comment]
Did the crash appears on the first resize ?

> Android devices can have as little as 16MB of memory available to a single application.

http://developer.android.com/training/displaying-bitmaps/index.html

If it's on the first resize you need to allocate more memory to your app.

http://stackoverflow.com/a/11275704

**Comment by yfuks** [comment]
No response i close.

**Comment by rahuljiresal** [comment]
This issue still exists. I need the images to be resized so my server API accepts them. But this always crashes while trying to resize them. From what I could tell, its the [BitmapFactory.decodeFile(realPath, options)](https://github.com/marcshilling/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L580)  that is the problem.

The solution would be to change the BitmapFactory options as mentioned here --
```
BitmapFactory.Options options = new BitmapFactory.Options();
 options.inJustDecodeBounds = false;
 options.inPreferredConfig = Config.RGB_565;
 options.inDither = true;
```

**Comment by flavordaaave** [comment]
I was running into the same issue. Adding `android:largeHeap="true"` to `<application>` tag in `AndroidManifest.xml` solved the issue for me on my physical Android but I'm a bit concerned that this  might still be an issue for some devices with less memory?!?
