### ISSUE TITLE
Crashes after image selected on Cyanogenmod with cropping

### ISSUE THREAD

**Issue by timsuchanek** [marcshilling/react-native-image-picker#154]
On Cyanogen 12.1.1, Android 5.1.1, after selecting a picture from gallery or taking picture with camera, the app crashes.

My config:

```js
export const uiPicker = {
	title: 'Choose a Picture', // specify null or empty string to remove the title
	cancelButtonTitle: 'Cancel',
	takePhotoButtonTitle: 'Take Photo...', // specify null or empty string to remove this button
	chooseFromLibraryButtonTitle: 'Choose from Library...', // specify null or empty string to remove this button
	cameraType: 'back', // 'front' or 'back'
	mediaType: 'photo', // 'photo' or 'video'
	maxWidth: 800, // photos only
	maxHeight: 800, // photos only
	aspectX: 1, // aspectX:aspectY, the cropping image's ratio of width to height
	aspectY: 1, // aspectX:aspectY, the cropping image's ratio of width to height
	quality: 0.2, // photos only
	angle: 0, // photos only
	allowsEditing: false, // Built in functionality to resize/reposition the image
	noData: false, // photos only - disables the base64 `data` field from being generated (greatly improves performance on large photos)
	storageOptions: { // if this key is provided, the image will get saved in the documents/pictures directory (rather than a temporary directory)
		skipBackup: true, // image will NOT be backed up to icloud
		path: 'images' // will save image at /Documents/images rather than the root
	}
};
```

The log message in adb:
```sh
D/QCameraParameters(  241): int qcamera::QCameraParameters::setAutoRotate(const qcamera::QCameraParameters&) set auto rotate: 0
E/mm-camera(  255): mct_pipeline_process_set:command=800000e
D/QCameraParameters(  241): int32_t qcamera::QCameraParameters::setNumOfSnapshot(): nBurstNum = 1, nExpnum = 1
D/LBSSystemMonitorService(  768): handleMessage what - 4
D/Wiper_jni(  768): Send Network Location.
W/JsonSuggestProvider( 2509): ext: null, mimeType: null, handles: false
D/ApplicationSuggestionService( 2509): handles? false
I/ActivityManager(  768): START u0 {act=com.android.camera.action.CROP dat=file:///data/data/com.cyngn.cameranext/files/crop-temp (has extras)} from uid 10038 on display 0
D/AndroidRuntime(24134): Shutting down VM
E/AndroidRuntime(24134): FATAL EXCEPTION: main
E/AndroidRuntime(24134): Process: com.cyngn.cameranext, PID: 24134
E/AndroidRuntime(24134): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=file:///data/data/com.cyngn.cameranext/files/crop-temp (has extras) }
E/AndroidRuntime(24134):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
E/AndroidRuntime(24134):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/AndroidRuntime(24134):        at android.app.Activity.startActivityForResult(Activity.java:3745)
E/AndroidRuntime(24134):        at android.app.Activity.startActivityForResult(Activity.java:3706)
E/AndroidRuntime(24134):        at com.android.camera.bi.do(SourceFile:1934)
E/AndroidRuntime(24134):        at com.android.camera.cb.onClick(SourceFile:456)
E/AndroidRuntime(24134):        at android.view.View.performClick(View.java:4789)
E/AndroidRuntime(24134):        at com.android.camera.ShutterButton.performClick(SourceFile:149)
E/AndroidRuntime(24134):        at android.view.View$PerformClick.run(View.java:19881)
E/AndroidRuntime(24134):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(24134):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(24134):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(24134):        at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(24134):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24134):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(24134):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(24134):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)


```

However, if I disable `aspectX` and `aspectY`, it works perfectly.
So obviously the feature doesn't exist in cyanogen or it has another name.

Maybe there could be a check in the app, if it is available or not.
A crash is a little bit hard.

Thanks!

**Comment by yfuks** [comment]
Hello @timsuchanek 
Are you using the last version of the package ?
And since you set ```allowsEditing: false``` there should be no crop and ```aspectX - aspectY``` are not used in this case

**Comment by timsuchanek** [comment]
Hi @yfuks yes, I'm using 0.18.3.

**Comment by babyLiyuan** [comment]
Yes, it always happens on Android. I'm using the 0.18.5. Everything seems OK when I change 
"allowsEditing" to false or it shows the same error as _tims_.

My suggestion is to separate the activity of capturing photo and cropping in the code. I hope this helps...

**Comment by yfuks** [comment]
Hi guys ! Sorry for the lack of response :yellow_heart: 

> My suggestion is to separate the activity of capturing photo and cropping in the code.

It's not a good solution :). An intent alone to handle crop ```com.android.camera.action.CROP``` is badly supported on **Android**.

> Maybe there could be a check in the app, if it is available or not.
A crash is a little bit hard.

Agree. Currently we check if we can create the activity or we print the above stack error (and it crash..). Will try to return the error to **react-native** and in the best case continue without cropping. Working on it ! :)

**Comment by yfuks** [comment]
I feel like you have an old implementation of the module since ```com.android.camera.action.CROP``` isn't used anymore.

Anyway i push some robustness code that will return the error to react-native if the activity don't exist. Tell me if that fix the crash for you.

**Comment by yfuks** [comment]
No response, i close
