### ISSUE TITLE
[Android] Unfortunately, Camera has stopped.

### ISSUE THREAD

**Issue by anton6** [marcshilling/react-native-image-picker#218]
Hi.

I am getting an error "Unfortunately, Camera has stopped." every time I am trying to take a photo. This appears to be caused when flag 'allowsEditing' is set to true. 

I get this issue on emulator Samsung Galaxy S5 - 4.4.4 (Genymotion), and also on my Huawei P8-lite. 

This is the error I get from logcat:
```
E/AndroidRuntime(15490): FATAL EXCEPTION: main
E/AndroidRuntime(15490): Process: com.huawei.camera, PID: 15490
E/AndroidRuntime(15490): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.android.camera.action.CROP dat=file:///data/data/com.huawei.camera/files/crop-temp (has extras) }
E/AndroidRuntime(15490): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1776)
E/AndroidRuntime(15490): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
E/AndroidRuntime(15490): 	at android.app.Activity.startActivityForResult(Activity.java:3801)
E/AndroidRuntime(15490): 	at android.app.Activity.startActivityForResult(Activity.java:3755)
E/AndroidRuntime(15490): 	at com.huawei.camera.ui.page.ReviewPage.handlePhotoDataResult(ReviewPage.java:159)
E/AndroidRuntime(15490): 	at com.huawei.camera.ui.page.ReviewPage.doReturnToCaller(ReviewPage.java:110)
E/AndroidRuntime(15490): 	at com.huawei.camera.ui.page.ReviewPage.access$000(ReviewPage.java:36)
E/AndroidRuntime(15490): 	at com.huawei.camera.ui.page.ReviewPage$1.onClick(ReviewPage.java:52)
E/AndroidRuntime(15490): 	at android.view.View.performClick(View.java:4766)
E/AndroidRuntime(15490): 	at android.view.View$PerformClick.run(View.java:19683)
E/AndroidRuntime(15490): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(15490): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15490): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15490): 	at android.app.ActivityThread.main(ActivityThread.java:5538)
E/AndroidRuntime(15490): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15490): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15490): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime(15490): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
W/System.err( 3016): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
W/System.err( 3016): 	at huawei.com.android.server.util.ReportTool.getUserType(ReportTool.java:86)
W/System.err( 3016): 	at huawei.com.android.server.util.ReportTool.isBetaUser(ReportTool.java:73)
W/System.err( 3016): 	at huawei.com.android.server.util.ReportTool.report(ReportTool.java:58)
W/System.err( 3016): 	at huawei.com.android.server.util.UserBehaviourRecord.appExitRecord(UserBehaviourRecord.java:65)
W/System.err( 3016): 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:1425)
W/System.err( 3016): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 3016): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 3016): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 3016): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
E/ReportTools( 3016): This is not beta user build
```

Does anyone know what the issue might be?
Thanks.

**Comment by marcshilling** [comment]
Can you run the Example project? The Example project works fine for me. I can take a photo with `allowsEditing: true` on a Samsung Galaxy S6 6.0.1

**Comment by eulphean** [comment]
Yes, I can confirm that this is reproable on OnePlusOne android device as well.

**Comment by marcshilling** [comment]
Some devices are not compatible with `allowsEditing: true`

**Comment by lesliesam** [comment]
I run into the same issue. @marcshilling What's your suggestion for this? We can't use allowsEditing for Android?

**Comment by tomazahlin** [comment]
I have the same problem. Setting allowsEditing: true does not help. Android 4.1.2

**Comment by marcshilling** [comment]
`allowsEditing` is no longer an option for Android. It caused too many problems. @tomazahlin are you using the latest version of this package on npm?

**Comment by tomazahlin** [comment]
Hi @marcshilling , yes I use the latest version. I found out that adding the option "allowsEditing" did not affect anything, like the docs say it is not supported. But I also solved my problem - the problem was that the emulator did not have a hardware camera attached (you can do this in "android avd" settings of the emulator. After I connected the laptop camera to it, it worked. So maybe in your code there should be check if camera is available?

Trace:
V/CameraHolder( 2633): open camera 0
E/CameraService( 1124): CameraService::connect X (pid 2633) rejected (invalid cameraId 0).
E/CameraHolder( 2633): fail to connect Camera
E/CameraHolder( 2633): java.lang.RuntimeException: Fail to connect to camera service
E/CameraHolder( 2633): 	at android.hardware.Camera.native_setup(Native Method)
E/CameraHolder( 2633): 	at android.hardware.Camera.<init>(Camera.java:306)
E/CameraHolder( 2633): 	at android.hardware.Camera.open(Camera.java:268)
E/CameraHolder( 2633): 	at com.android.camera.CameraHolder.open(CameraHolder.java:131)
E/CameraHolder( 2633): 	at com.android.camera.Util.openCamera(Util.java:267)
E/CameraHolder( 2633): 	at com.android.camera.Camera$4.run(Camera.java:1100)
E/CameraHolder( 2633): 	at java.lang.Thread.run(Thread.java:856)
W/dalvikvm( 2633): threadid=10: thread exiting with uncaught exception (group=0xa668f228)
E/AndroidRuntime( 2633): FATAL EXCEPTION: Thread-106
E/AndroidRuntime( 2633): java.lang.RuntimeException: openCamera failed
E/AndroidRuntime( 2633): 	at com.android.camera.Util.openCamera(Util.java:272)
E/AndroidRuntime( 2633): 	at com.android.camera.Camera$4.run(Camera.java:1100)
E/AndroidRuntime( 2633): 	at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 2633): Caused by: com.android.camera.CameraHardwareException: java.lang.RuntimeException: Fail to connect to camera service
E/AndroidRuntime( 2633): 	at com.android.camera.CameraHolder.open(CameraHolder.java:135)
E/AndroidRuntime( 2633): 	at com.android.camera.Util.openCamera(Util.java:267)
E/AndroidRuntime( 2633): 	... 2 more
E/AndroidRuntime( 2633): Caused by: java.lang.RuntimeException: Fail to connect to camera service
E/AndroidRuntime( 2633): 	at android.hardware.Camera.native_setup(Native Method)
E/AndroidRuntime( 2633): 	at android.hardware.Camera.<init>(Camera.java:306)
E/AndroidRuntime( 2633): 	at android.hardware.Camera.open(Camera.java:268)
E/AndroidRuntime( 2633): 	at com.android.camera.CameraHolder.open(CameraHolder.java:131)
E/AndroidRuntime( 2633): 	... 3 more
