### ISSUE TITLE
[Android] Cancel selecting will cause crash sometimes

### ISSUE THREAD

**Issue by kiliwalk** [marcshilling/react-native-image-picker#219]
Version `0.18.14`, `ReactNative 0.26.2`, `ANDROID 4.4.2`, real device.
Not always came this problem, but sometimes.
Put it here, and I will try to check the code later. And hope others help, thanks

```
E/AndroidRuntime(15793): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent {  }} to activity {com.xxx/com.xxx.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(15793): 	at android.app.ActivityThread.deliverResults(ActivityThread.java)
E/AndroidRuntime(15793): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java)
E/AndroidRuntime(15793): 	at android.app.ActivityThread.access$1300(ActivityThread.java)
E/AndroidRuntime(15793): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
E/AndroidRuntime(15793): 	at android.os.Handler.dispatchMessage(Handler.java)
E/AndroidRuntime(15793): 	at android.os.Looper.loop(Looper.java)
E/AndroidRuntime(15793): 	at android.app.ActivityThread.main(ActivityThread.java)
E/AndroidRuntime(15793): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15793): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15793): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/AndroidRuntime(15793): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
E/AndroidRuntime(15793): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15793): Caused by: java.lang.NullPointerException
E/AndroidRuntime(15793): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java)
E/AndroidRuntime(15793): 	at android.content.ContentResolver.query(ContentResolver.java)
E/AndroidRuntime(15793): 	at android.content.ContentResolver.query(ContentResolver.java)
E/AndroidRuntime(15793): 	at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:449)
E/AndroidRuntime(15793): 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:351)
E/AndroidRuntime(15793): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:198)
E/AndroidRuntime(15793): 	at com.facebook.react.ReactInstanceManagerImpl.onActivityResult(ReactInstanceManagerImpl.java:599)
E/AndroidRuntime(15793): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:180)
E/AndroidRuntime(15793): 	at android.app.Activity.dispatchActivityResult(Activity.java)
E/AndroidRuntime(15793): 	... 12 more
```

**Comment by marcshilling** [comment]
I cannot reproduce this in the Example project running on Samsung Galaxy S6 6.0.1

**Comment by marcshilling** [comment]
No response, closing.
