### ISSUE TITLE
[Android] need to implement onNewIntent of ActivityEventListener

### ISSUE THREAD

**Issue by rilyu** [marcshilling/react-native-image-picker#275]
hi,

Can you add onNewIntent function for ImagePickerModule.java? I use react-native-image-picker on react native v0.30.0 catch this error:

```
java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onNewIntent(android.content.Intent)"
 at com.facebook.react.bridge.ReactContext.onNewIntent(ReactContext.java:169)
 at com.facebook.react.ReactInstanceManagerImpl.onNewIntent(ReactInstanceManagerImpl.java:483)
 at com.facebook.react.ReactActivity.onNewIntent(ReactActivity.java:183)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1221)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1233)
 at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2725)
 at android.app.ActivityThread.performNewIntents(ActivityThread.java:2737)
 at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2746)
 at android.app.ActivityThread.access$1700(ActivityThread.java:188)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loop(Looper.java:194)
 at android.app.ActivityThread.main(ActivityThread.java:5701)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Cause:

https://github.com/facebook/react-native/releases/tag/v0.30.0

Android
Native modules implementing ActivityEventListener now need to implement onNewIntent(Intent Intent)

**Comment by npomfret** [comment]
Does anyone have a solution for this?  Using RN 0.32, android 5.1, react-native-image-picker 0.21.5 - its still crashing.
