### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lekenny** [marcshilling/react-native-image-picker#287]
'java.lang.NullPointerException
	atcom.imagepicker.ImagePickerModule.getBase64StringFromFile(ImagePickerModule.java:559)
	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:436)
	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)'

**Comment by yfuks** [comment]
Can you copy paste your code ?
