### ISSUE TITLE
Android 7.0 crashes when taking photo or video

### ISSUE THREAD

**Issue by superandrew213** [marcshilling/react-native-image-picker#302]
Android: 7.0
react-native-image-picker: 0.22.1

Tested on sim only. Crashes now and then when you take a photo. Crashes all the time when taking video.

**Comment by luisfuertes** [comment]
+1 on Android 4.4 and Android 5.0. When select photo in gallery, it works, but when try to take a photo component crash

**Comment by marcshilling** [comment]
I can't reproduce this by running the Example project on a Galaxy S6 Android 6.0.1. Both taking a photo and taking a video work fine.

Are you guys able to run the example project? Can you post your image picker options or a crash log?

**Comment by superandrew213** [comment]
Only happening on Android 7 for me. No issues with the other Android versions.

For take photo:

```
--------- beginning of crash
09-09 06:49:24.101  3103  3103 E AndroidRuntime: FATAL EXCEPTION: main
09-09 06:49:24.101  3103  3103 E AndroidRuntime: Process: com.sensio.instapreview, PID: 3103
09-09 06:49:24.101  3103  3103 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=null} to activity {com.xxx.xxx/com.xxx.xxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData android.content.Intent.getClipData()' on a null object reference
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
09-09 06:49:24.101  3103  3103 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData android.content.Intent.getClipData()' on a null object reference
```

For take video:

```
09-09 07:02:07.816  1228  1468 D AudioFlinger: mixer(0xef283a80) throttle end: throttle time(11)
09-09 07:02:07.821  3374  3547 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
09-09 07:02:07.821  3374  3547 W ViewRootImpl[MainActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_HOVER_ENTER, actionButton=0, id[0]=0, x[0]=318.27832, y[0]=848.5156, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=943930, downTime=943819, deviceId=0, source=0x1002 }
09-09 07:02:07.821  3374  3547 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
09-09 07:02:07.821  3374  3547 W ViewRootImpl[MainActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_HOVER_ENTER, actionButton=0, id[0]=0, x[0]=318.27832, y[0]=848.5156, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=943930, downTime=943819, deviceId=0, source=0x1002 }
09-09 07:02:07.821  3374  3547 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
09-09 07:02:07.821  3374  3547 W ViewRootImpl[MainActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_HOVER_MOVE, actionButton=0, id[0]=0, x[0]=318.27832, y[0]=848.5156, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=943930, downTime=943819, deviceId=0, source=0x1002 }
09-09 07:02:07.821  3374  3547 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
09-09 07:02:07.825  1485  1806 I ActivityManager: START u0 {act=android.media.action.VIDEO_CAPTURE cmp=com.android.camera/.VideoCamera (has extras)} from uid 10066 on display 0
09-09 07:02:07.836  1485  2414 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@7d78292 attribute=null, token = android.os.BinderProxy@d805f71
09-09 07:02:07.847  1228  1468 D AudioFlinger: mixer(0xef283a80) throttle end: throttle time(11)
09-09 07:02:07.848  3563  3563 W art     : Unexpected CPU variant for X86 using defaults: x86_64
09-09 07:02:07.855  1485  1704 I ActivityManager: Start proc 3563:com.android.camera/u0a44 for activity com.android.camera/.VideoCamera
09-09 07:02:07.873  1221  1965 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x933 imply creation of host color buffer
09-09 07:02:07.884  1485  1506 D         : HostConnection::get() New Host Connection established 0x7ffed5c34280, tid 1506
09-09 07:02:07.963  1229  1229 V EmulatedCamera_Camera: getCameraInfo
09-09 07:02:07.963  1229  1229 V EmulatedCamera_BaseCamera: getCameraInfo
09-09 07:02:07.968  1229  1513 V EmulatedCamera_Camera: getCameraInfo
09-09 07:02:07.968  1229  1513 V EmulatedCamera_BaseCamera: getCameraInfo
09-09 07:02:07.993  3563  3580 V CameraHolder: open camera 0
09-09 07:02:07.995  1229  1229 I CameraService: CameraService::connect call (PID -1 "com.android.camera", camera ID 0) for HAL version default and Camera API version 1
09-09 07:02:07.995  1229  1229 V EmulatedCamera_Camera: getCameraInfo
09-09 07:02:07.995  1229  1229 V EmulatedCamera_BaseCamera: getCameraInfo
09-09 07:02:08.012  1236  3581 D NuPlayerDriver: notifyListener_l(0xe7e8c780), (1, 0, 0), loop setting(0, 0)
09-09 07:02:08.040  1236  3583 D NuPlayerDriver: notifyListener_l(0xe7e8c720), (1, 0, 0), loop setting(0, 0)
09-09 07:02:08.051  1236  3585 D NuPlayerDriver: notifyListener_l(0xe96a91a0), (1, 0, 0), loop setting(0, 0)
09-09 07:02:08.055  1229  1229 I CameraFlashlight: Opening camera 0
09-09 07:02:08.055  1229  1229 V EmulatedCamera_Camera: getCameraInfo
09-09 07:02:08.055  1229  1229 V EmulatedCamera_BaseCamera: getCameraInfo
09-09 07:02:08.055  1229  1229 V EmulatedCamera_Camera: connectCamera
09-09 07:02:08.055  1229  1229 V EmulatedCamera_FakeDevice: connectDevice
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier: setCallbacks: 0xedb3ad30, 0xedb3ad80, 0xedb3aea0, 0xedb3afc0 (0xed7c3a00)
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier: enableMessage: msg_type = 0xc0d
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_ERROR
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_FOCUS
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_ZOOM
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_PREVIEW_METADATA
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier: **** Currently enabled messages:
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_ERROR
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_FOCUS
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_ZOOM
09-09 07:02:08.055  1229  1229 V EmulatedCamera_CallbackNotifier:     CAMERA_MSG_PREVIEW_METADATA
09-09 07:02:08.056  1229  1513 V EmulatedCamera_Camera: getCameraInfo
09-09 07:02:08.057  1229  1513 V EmulatedCamera_BaseCamera: getCameraInfo
09-09 07:02:08.059  3563  3580 E AndroidRuntime: FATAL EXCEPTION: Thread-2
09-09 07:02:08.059  3563  3580 E AndroidRuntime: Process: com.android.camera, PID: 3563
09-09 07:02:08.059  3563  3580 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.hardware.Camera$Size.width' on a null object reference
09-09 07:02:08.059  3563  3580 E AndroidRuntime: 	at com.android.camera.VideoCamera.getDesiredPreviewSize(VideoCamera.java:799)
09-09 07:02:08.059  3563  3580 E AndroidRuntime: 	at com.android.camera.VideoCamera.readVideoPreferences(VideoCamera.java:781)
09-09 07:02:08.059  3563  3580 E AndroidRuntime: 	at com.android.camera.VideoCamera.-wrap3(VideoCamera.java)
09-09 07:02:08.059  3563  3580 E AndroidRuntime: 	at com.android.camera.VideoCamera$1.run(VideoCamera.java:389)
09-09 07:02:08.059  3563  3580 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
09-09 07:02:08.061  1485  2472 W ActivityManager:   Force finishing activity com.android.camera/.VideoCamera
09-09 07:02:08.063  1485  2472 W ActivityManager:   Force finishing activity com.xxx.xxx/.MainActivity
```

**Comment by marcshilling** [comment]
I can't upgrade to Android 7 at the moment so I'm not gonna be able to look into this if it's isolated to that. It would be great if you could set some breakpoints and get your feet wet in the code to find the issue!

**Comment by superandrew213** [comment]
Ok I'll see what I can do. I'm also only testing on simulator. Not sure if this is happening on device

**Comment by marcshilling** [comment]
Wait...you're testing on the simulator and it's crashing when taking a photo? Well that makes a lot of sense because your simulator doesn't have a camera...

**Comment by superandrew213** [comment]
You can take a photo on Android sim. It's different to iPhone sim.

**Comment by marcshilling** [comment]
Well, I'd still argue you should really try running it on a real device. If it works on device this is a non-issue.

**Comment by superandrew213** [comment]
I'd love to but I don't have an Android device.

**Comment by AlexSchwabauer** [comment]
I experienced the same issue while having another rn-module installed. The issue is that your Activity request codes are quite common ints, causing a clash of eventListeners. See #291

**Comment by marcshilling** [comment]
Can you guys try `v0.22.8` on npm? I made the request codes more unique.

**Comment by tegument** [comment]
I can confirm that v0.22.9 works on Android 7 after the recent fix.  I was having the same issue before with 0.22.7, crashing on pick from photo / gallery.

**Comment by marcshilling** [comment]
This issue seems outdated at this point. Please open a new issue if anyone is still getting a crash with the latest version.
