### ISSUE TITLE
unfortunately gallery has stopped when select "choose from library"

### ISSUE THREAD

**Issue by wzy535** [marcshilling/react-native-image-picker#372]
Hi, I got errors, when touch "choose from library". it shows "unfortunately gallery has stopped"
here is the adb logcat. 
react-native version: 0.35
Please help, thanks in advance!

```
10-27 05:12:23.562  2635  2635 V NFC     : this device does not have NFC support
10-27 05:12:23.648  2635  2635 D Gallery.MultiSetSync: onSyncDone: Local albums #pending=1
10-27 05:12:23.648  2635  2635 D Gallery.MultiSetSync:   request sync: Local albums
10-27 05:12:23.648  2635  2635 D Gallery.MultiSetSync: onSyncDone: picasa #pending=0
10-27 05:12:23.648  2635  2635 D Gallery.MultiSetSync:   request sync: picasa
10-27 05:12:23.685  2635  2651 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
10-27 05:12:23.689  2635  2635 D         : HostConnection::get() New Host Connection established 0xe7debc40, tid 2635
10-27 05:12:23.720   758  1133 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.gallery3d/.app.GalleryActivity (has extras)} from uid 10008 on display 0
10-27 05:12:23.755   452   832 D AudioFlinger: mixer(0xf1e80000) throttle end: throttle time(11)
10-27 05:12:23.762  2635  2651 D libEGL  : loaded /system/lib/egl/libEGL_emulation.so
10-27 05:12:23.763  2635  2651 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_emulation.so
10-27 05:12:23.767  2635  2651 D libEGL  : loaded /system/lib/egl/libGLESv2_emulation.so
10-27 05:12:23.770  2635  2651 D         : HostConnection::get() New Host Connection established 0xe7debd80, tid 2651
10-27 05:12:23.800  2635  2651 I OpenGLRenderer: Initialized EGL, version 1.4
10-27 05:12:23.854  1134  1283 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdea28310
10-27 05:12:23.920  2635  2651 W EGL_emulation: eglSurfaceAttrib not implemented
10-27 05:12:23.920  2635  2651 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe98a8f00, error=EGL_SUCCESS
10-27 05:12:23.989  2635  2648 D         : HostConnection::get() New Host Connection established 0xee9926f0, tid 2648
10-27 05:12:23.992  2635  2648 E AndroidRuntime: FATAL EXCEPTION: GLThread 171
10-27 05:12:23.992  2635  2648 E AndroidRuntime: Process: com.android.gallery3d, PID: 2635
10-27 05:12:23.992  2635  2648 E AndroidRuntime: java.lang.IllegalArgumentException: No config chosen
10-27 05:12:23.992  2635  2648 E AndroidRuntime:        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:870)
10-27 05:12:23.992  2635  2648 E AndroidRuntime:        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
10-27 05:12:23.992  2635  2648 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
10-27 05:12:23.992  2635  2648 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
10-27 05:12:24.006   758   915 W ActivityManager:   Force finishing activity com.android.gallery3d/.app.GalleryActivity
10-27 05:12:24.121   758   915 D         : HostConnection::get() New Host Connection established 0xdccbf480, tid 915
10-27 05:12:24.145   781   781 E EGL_emulation: tid 781: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
10-27 05:12:24.238   758   758 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 243ms
10-27 05:12:24.238   758   772 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=1 for 209ms
10-27 05:12:24.284   758  1934 I OpenGLRenderer: Initialized EGL, version 1.4
10-27 05:12:24.392   758  1934 W EGL_emulation: eglSurfaceAttrib not implemented
10-27 05:12:24.392   758  1934 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdcdbdcc0, error=EGL_SUCCESS
10-27 05:12:24.456   758  1167 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@dcb0fab (uid=10037 pid=2635)
10-27 05:12:24.541  1134  1283 W EGL_emulation: eglSurfaceAttrib not implemented
10-27 05:12:24.542  1134  1283 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe03e09c0, error=EGL_SUCCESS
10-27 05:12:24.673  2635  2635 V StateManager: destroy
10-27 05:12:24.736  2635  2651 E Surface : getSlotFromBufferLocked: unknown buffer: 0xe98a33e0
10-27 05:12:28.732  2635  2648 I Process : Sending signal. PID: 2635 SIG: 9
10-27 05:12:28.735   758  1934 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdeb69d10
10-27 05:12:28.750   758   915 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@47a119e attribute=null, token = android.os.BinderProxy@fdfd7cb
10-27 05:12:28.752   758   769 D GraphicsStats: Buffer count: 6
10-27 05:12:28.757   758  1132 I ActivityManager: Process com.android.gallery3d (pid 2635) has died
10-27 05:12:28.991   758   777 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-27 05:12:53.113   100   100 D Genyd   : Received Set Clipboard
10-27 05:12:53.113   100   100 D Genymotion: Received Set Clipboard
10-27 05:14:02.653   758  1861 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1010653, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_PROBE}
```

**Comment by yfuks** [comment]
Try opening the gallery app. If it crash that's an emulator issue

**Comment by JakeRuth** [comment]
So this is a HUGE issue for me as well.  I can open the photo gallery standalone.

Here is what changed for me:
- I was using `0.22.12` of this plugin with xcode 7.2 oxs 10.10
- Then I updated osx to Sierra 10.12 and I updated to xcode 8 cause xcode 7 basically didn't work on Sierra.... (one of the millions of horrific issues I'm dealing with rn)
- I didn't update this plugin, just the os and xcode as I said above and now the simulator is crashing when I click to choose a photo

Some other new behavior I saw was that before updating everything, when I clicked 'Take a Photo' in the simulator I got a console message in xcode saying that it wasn't supported.  After updating now when I click Take a Photo this block of code actually catches the selection the the message that the camera isn't supported exists in `response.error` as a string.

```
UIImagePickerManager.showImagePicker(this._getImagePickerOptions(), (response) => {
     // response.error = "Camera not available on simulator"
}
```
 
![simulator screen shot oct 27 2016 11 09 39 am](https://cloud.githubusercontent.com/assets/7349551/19773000/f78e4cd2-9c35-11e6-909b-91f047dd970c.png)

This is what I see in xcode when I click the choose photo option (again, I can open the gallery from the ios home)
![screen shot 2016-10-27 at 11 18 40 am](https://cloud.githubusercontent.com/assets/7349551/19773357/4337b230-9c37-11e6-9750-4c136539a8a9.png)

I am going to try other react native plugins to see if they have the same issue, this is pretty critical for our app

**Comment by JakeRuth** [comment]
@wzy535 If you are still having trouble this is what fixed it for me, and @yfuks was correct (and confirmed in my post/investigation above) that this issue isn't related to this plugin.
[This stackoverflow accepted answer has all you need](http://stackoverflow.com/questions/40281071/image-picker-crash-on-simulator)

Back to coding and uploading photos!

**Comment by marcshilling** [comment]
No action here and seems like solutions have been posted.
