### ISSUE TITLE
[Android] IOException: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by atom992** [marcshilling/react-native-image-picker#72]
when I pick up a image from system,I got this error:
```
W/System.err( 5279): java.io.IOException: open failed: ENOENT (No such file or directory)
W/System.err( 5279): 	at java.io.File.createNewFile(File.java:941)
W/System.err( 5279): 	at com.imagepicker.ImagePickerModule.getResizedImage(ImagePickerModule.java:331)
W/System.err( 5279): 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:245)
W/System.err( 5279): 	at com.imagepicker.ImagePickerPackage.handleActivityResult(ImagePickerPackage.java:46)
W/System.err( 5279): 	at com.jarvis.MainActivity.onActivityResult(MainActivity.java:65)
W/System.err( 5279): 	at android.app.Activity.dispatchActivityResult(Activity.java:6139)
W/System.err( 5279): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3535)
W/System.err( 5279): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
W/System.err( 5279): 	at android.app.ActivityThread.access$1300(ActivityThread.java:144)
W/System.err( 5279): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
W/System.err( 5279): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 5279): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 5279): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 5279): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5279): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 5279): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 5279): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/System.err( 5279): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err( 5279): 	at libcore.io.Posix.open(Native Method)
W/System.err( 5279): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/System.err( 5279): 	at java.io.File.createNewFile(File.java:934)
W/System.err( 5279): 	… 16 more
W/System.err( 5279): 	at com.jarvis.MainActivity.onActivityResult(MainActivity.java:65)
W/System.err( 5279): 	at android.app.Activity.dispatchActivityResult(Activity.java:6139)
W/System.err( 5279): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3535)
W/System.err( 5279): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
W/System.err( 5279): 	at android.app.ActivityThread.access$1300(ActivityThread.java:144)
W/System.err( 5279): 	at android.app.ActivityThread$H.handleMessage(Activity
```

**Comment by yfuks** [comment]
What kind of image ? (photo, facebook, dropbox..)

I look into this issues and i find the folowing : http://stackoverflow.com/a/11620848
We actually write our file in external storage

try to add the folowing in your AndroidManifest
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

If that don't work try to reproduce multiple times, if that work once then work everytime it couldmaybe say that the module need to create image in a custom directory

**Comment by atom992** [comment]
I am picking up a photo from filesystem.
 I have already add the following permission:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
but the same error.

**Comment by atom992** [comment]
when Download area is unselectable, I click the photo,I got the following error:
```
AUDIO_OUTPUT_FLAG_FAST denied by client
```

**Comment by yfuks** [comment]
What is your device **API** ?

**Comment by atom992** [comment]
android 5.0.1 (API 21)

**Comment by yfuks** [comment]
Ok, i maybe found something, can you tell me if you have a picture directory on your device ?

In the module try to replace android/src/main/java/com/imagepicker/ImagePickerModule.java
at line 326 :
```java
File f = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES) + File.separator + filname +".jpg");
try {
  f.createNewFile();
} catch (IOException e) {
  e.printStackTrace();
}
```
into :
```java
File path = Environment.getExternalStoragePublicDirectory(
            Environment.DIRECTORY_PICTURES);
File file = new File(path, filname +".jpg");
try {
  // Make sure the Pictures directory exists.
  path.mkdirs();

  f.createNewFile();
} catch (IOException e) {
  e.printStackTrace();
}
```

**Comment by atom992** [comment]
yes,my SDCARD Directory only have following Directory:
Android
DCIM
Download
LOST.DIR

**Comment by yfuks** [comment]
Just apply the previous fix and tell me if it work for you.
Make sure to rebuild your apk (```react-native run-android```)

**Comment by atom992** [comment]
yes, it works.

**Comment by yfuks** [comment]
It's a know issues #58
Will try to fix it as soon as possible.

Sorry for the inconvenience

**Comment by atom992** [comment]
ok I will close this issue.Thank you.

**Comment by atom992** [comment]
just fine it do work, but every time I pick up a photo, The photo will be created  other copy.

**Comment by yfuks** [comment]
Don't set the folowing options : 
**maxHeight, maxWidth, quality**

or set as folow:
```javascript
{
  maxWidth: 0,
  maxHeight: 0,
  quality: 100
}
```

**Comment by agrass** [comment]
HI @yfuks, I'm having this problem some times. It's there another workaround?

**Comment by sriramr98** [comment]
This problem arises because of two main reasons.

The file doesn't exist in the storage
You do not have permission to write files to the system.

In devices higher than Android 6.0, then you need to ask permissions in runtime.

If the file does not exist, you can do that like this

`file.createFile()` or `file.mkdirs()` depending on your file type.

**Comment by codemaker2015** [comment]
If you are building your app with target version API level greater than 27 then the storage access disabled by default. If you want to enable it quickly, add the following line in your AndroidManifest.xml file.

```
<manifest ... >
  <application 
       android:requestLegacyExternalStorage="true"   //add this line 
       ... >
    ...
  </application>
</manifest>
```
