### ISSUE TITLE
[Android] Build failed

### ISSUE THREAD

**Issue by Raisin-Man** [marcshilling/react-native-image-picker#76]
Hey guys,

I used the guide to add image picker to my app, however, when I run react-native run-android I run into this issue

<img width="790" alt="screen shot 2016-01-08 at 4 36 09 am" src="https://cloud.githubusercontent.com/assets/8294708/12198050/69cf2890-b5c1-11e5-8c50-fe29abcc8f07.png">

I saw that someone had this issue in the past, but there was a fix for it. However, I'm having this issue now. Thanks for your help!

**Comment by yfuks** [comment]
It's probably a problem in your android/settings.gradle

Can you send more infos ?
just run the command with --info or --debug

**Comment by AhmedMAtia** [comment]
hi
I have same issue React native 0.18.0-rc

```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module ReactNativeCalendarAndroid : Configuration with name 'default' not found.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:85)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.UnknownProjectException: Cannot evaluate module ReactNativeCalendarAndroid : Configuration with name 'default' not found.
	at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:666)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencyForConfig(DependencyManager.java:235)
	at com.android.build.gradle.internal.DependencyManager.resolveDependencies(DependencyManager.java:135)
	at com.android.build.gradle.internal.TaskManager.resolveDependencies(TaskManager.java:317)
	at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:573)
	at com.android.build.gradle.internal.VariantManager$8.call(VariantManager.java:570)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
	at com.android.builder.profile.Recorder$record.call(Unknown Source)
	at com.android.builder.profile.Recorder$record.call(Unknown Source)
	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:69)
	at com.android.build.gradle.internal.VariantManager.createVariantData(VariantManager.java:569)
	at com.android.build.gradle.internal.VariantManager.createVariantDataForProductFlavors(VariantManager.java:722)
	at com.android.build.gradle.internal.VariantManager.populateVariantDataList(VariantManager.java:442)
	at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:258)
	at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy:483)
	at com.android.build.gradle.BasePlugin$_createAndroidTasks_closure15.doCall(BasePlugin.groovy)
	at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:482)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:415)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
	at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
	at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.groovy:54)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13.doCall(BasePlugin.groovy:414)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 33 more
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:81)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:210)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:71)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:34)
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:69)
	at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
	at com.android.build.gradle.internal.DependencyManager.ensureConfigured(DependencyManager.java:664)
	... 65 more


BUILD FAILED
```

**Comment by Raisin-Man** [comment]
Appending --info or --debug isn't giving me any additional output in the terminal. In my android/settings.gradle, I added the lines

    include ':react-native-image-picker'
    project(':react-native-image-picker').projectDir = new File(settingsDir, '../node_modules/react-native-image-picker/android')

Where is `'../node_modules/react-native-image-picker/android'` supposed to be pointing to?

**Comment by Raisin-Man** [comment]
I figured it out. I ran the line `npm install react-native-image-picker@latest --save` in my root folder, not in the app's folder. Thanks!
